spring.application.name=appointment-pack-api

# Postgres DB Properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Properties
app.jwt.secret=${JWT_SECRET}

# Enable Problem Details ErrorResponse
spring.mvc.problemdetails.enabled=true

# File Storage Properties
appointment-pack.documents.storage-directory=${DOCUMENT_STORAGE_DIRECTORY:./data/documents}
appointment-pack.documents.maximum-file-size-bytes=10485760

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Document Processing Service Properties
appointment-pack.document-processing.base-url=${DOCUMENT_PROCESSING_BASE_URL:http://127.0.0.1:8000}
appointment-pack.document-processing.api-key=${DOCUMENT_PROCESSING_API_KEY}

appointment-pack.document-processing.connect-timeout-seconds=5
appointment-pack.document-processing.response-timeout-seconds=120
