spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

appointment-pack.frontend.base-url=${FRONTEND_BASE_URL}
appointment-pack.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
appointment-pack.email.from=${MAIL_FROM}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}

appointment-pack.documents.storage-directory=${DOCUMENT_STORAGE_DIRECTORY}
appointment-pack.appointment-packs.storage-directory=${APPOINTMENT_PACK_STORAGE_DIRECTORY}
appointment-pack.document-processing.base-url=${DOCUMENT_PROCESSING_BASE_URL}